#!/usr/bin/env python3
"""Deterministic offline Chinese font build. Requires docs/fonts/requirements.txt."""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import unicodedata
import importlib.metadata
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
REL = Path('lxgw-neo-zhisong/v1.067')
SHA = '32b398f9c6278c4ed34f413077add2c2f3c84034d463af2b9cb98f12c4c2c6cd'
# Explicit ranges include future encoded extensions; intersect with the actual source cmap.
HAN = [(0x3400,0x4DBF),(0x4E00,0x9FFF),(0xF900,0xFAFF),(0x20000,0x2FA1F),(0x30000,0x3347F)]
PUNCT = [(0x2000,0x206F),(0x3000,0x303F),(0xFE10,0xFE1F),(0xFE30,0xFE4F),(0xFF01,0xFF65)]
PRIORITY = '人类圖类图出生时间年月日时分地点城市国家设置設定语言語言字体字體恢复恢復原始默认默認保存取消确认確認返回主页主頁今天当前當前行运運关系關係中心通道闸門门人生角色定义定義能量类型類型内在权威權威策略非自己主题主題显示顯示个人個人资料資料加载載中请选择請選擇搜索关闭關閉开启開啟下载下載导出導出中文简体簡體繁体帮助幫助乾坤屯蒙需讼訟师師比小畜履泰否同人大有谦謙豫随隨蛊蠱临臨观觀噬嗑贲賁剥剝复復无妄大畜颐頤大过過坎离離咸恒恆遁大壮壯晋晉明夷家人睽蹇解损損益夬姤萃升困井革鼎震艮渐漸归妹歸丰豐旅巽兑兌涣渙节節中孚小过既济濟未济，。；：！？、（）《》「」『』【】……—'

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def eligible(cp):
    return (any(a <= cp <= b for a,b in HAN) or cp in (0x3005,0x3007,0x303B) or
            (any(a <= cp <= b for a,b in PUNCT) and (unicodedata.category(chr(cp)).startswith('P') or cp == 0x3000)))

def cmap(font):
    return set().union(*(set(t.cmap) for t in font['cmap'].tables if t.isUnicode() and t.format != 14))

def ranges(points):
    result=[]
    for cp in sorted(points):
        if result and cp == result[-1][1]+1:
            result[-1][1]=cp
        else:
            result.append([cp,cp])
    return ','.join(f'U+{a:X}' if a==b else f'U+{a:X}-{b:X}' for a,b in result)

def face(family,url,points,fmt):
    return f"@font-face {{\n  font-family: '{family}';\n  src: url('{url}') format('{fmt}');\n  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n  unicode-range: {ranges(points)};\n}}\n"

def text(path, value):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(value,encoding='utf-8',newline='\n')

def build(out):
    for package,version in [('fonttools','4.60.1'),('brotli','1.1.0')]:
        assert importlib.metadata.version(package)==version, f'Install pinned {package}=={version}'
    src=ROOT/'public/fonts'/REL/'source/LXGWNeoZhiSong.ttf'
    assert src.stat().st_size==10468036 and digest(src)==SHA, 'Unexpected LXGW source'
    base=TTFont(src,recalcTimestamp=False)
    source=cmap(base)
    selected={cp for cp in source if eligible(cp)}
    priority=sorted(selected & set(map(ord,PRIORITY+(ROOT/'docs/fonts/priority.txt').read_text(encoding='utf-8'))))
    remainder=sorted(selected-set(priority))
    groups=[priority[i:i+256] for i in range(0,len(priority),256)]
    groups += [remainder[i:i+256] for i in range(0,len(remainder),256)]
    dest=out/REL
    dest.mkdir(parents=True,exist_ok=True)
    css='/* Generated by scripts/build-chinese-fonts.py; IPA Font License 1.0. */\n'
    entries=[]
    union=set()
    for index,points in enumerate(groups):
        font=TTFont(src,recalcTimestamp=False)
        options=subset.Options()
        options.recalc_timestamp=False
        options.canonical_order=True
        options.name_IDs=['*']
        options.name_legacy=True
        options.name_languages=['*']
        options.layout_features=['*']
        worker=subset.Subsetter(options=options)
        # Preserve punctuation UVS mappings as well as ordinary cmap entries.
        selectors={tup for t in font['cmap'].tables if t.format==14 for tup,values in t.uvsDict.items() if any(cp in points for cp,_ in values)}
        worker.populate(unicodes=set(points)|selectors)
        worker.subset(font)
        font.flavor='woff2'
        name=f'td-zhisong-p2-{index:03d}.woff2'
        font.save(dest/name)
        actual=cmap(TTFont(dest/name))
        assert actual==set(points), f'cmap mismatch {name}'
        assert not union & actual, 'Overlapping shards'
        union |= actual
        css+=face('TD LXGW Neo ZhiSong',name,points,'woff2')
        entries.append({'file':name,'bytes':(dest/name).stat().st_size,'sha256':digest(dest/name),'count':len(points),'unicodeRange':ranges(points)})
        if index%20==0: print(f'Built {index+1}/{len(groups)}',flush=True)
    assert union==selected
    assert not any(cp<128 or 0x4DC0<=cp<=0x4DFF for cp in union)
    assert set(map(ord,'乾坤坎离離震艮巽兑兌'))<=union
    text(dest/'font.css',css)
    ipa=ROOT/'public/fonts/ipa-original/ipamjm.ttf'
    assert digest(ipa)=='a3e84f495f3c388db7a1473bf1985c1c076d0c814100f10a027ca6853eb1e8cb', 'Unexpected original IPA font'
    ipa_font=TTFont(ipa,recalcTimestamp=False)
    ipa_points={cp for cp in cmap(ipa_font) if eligible(cp)}
    text(out/'ipa-original/font.css',face('TD IPA Original','ipamjm.ttf',ipa_points,'truetype'))
    report={'schema':1,'license':'IPA Font License 1.0','source':{'file':'source/LXGWNeoZhiSong.ttf','sha256':SHA,'bytes':src.stat().st_size},'tools':{'fonttools':'4.60.1','brotli':'1.1.0','unicodeData':unicodedata.unidata_version},'policy':'Han blocks and Chinese/general punctuation only; no ASCII, Latin, digits or diagram symbols. Actual source cmap intersection.','sourceCmapCount':len(source),'sourceUnicodeRange':ranges(source),'priorityCount':len(priority),'priorityShardCount':(len(priority)+255)//256,'selectedCount':len(selected),'selectedUnicodeRange':ranges(selected),'excludedUnicodeRange':ranges(source-selected),'coverageUnionExact':True,'disjoint':True,'shardCount':len(entries),'woff2Bytes':sum(e['bytes'] for e in entries),'maxShardBytes':max(e['bytes'] for e in entries),'cssSha256':digest(dest/'font.css'),'ipa':{'file':'ipa-original/ipamjm.ttf','sha256':digest(ipa),'bytes':ipa.stat().st_size,'selectedCount':len(ipa_points),'cssSha256':digest(out/'ipa-original/font.css')},'shards':entries}
    text(dest/'manifest.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    return report

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--verify',action='store_true',help='Rebuild into temporary directory and compare all generated bytes')
    args=parser.parse_args()
    if args.verify:
        with tempfile.TemporaryDirectory(prefix='td-font-check-') as temp:
            out=Path(temp)
            report=build(out)
            for file in out.rglob('*'):
                if file.is_file():
                    assert file.read_bytes()==(ROOT/'public/fonts'/file.relative_to(out)).read_bytes(), f'Non-reproducible: {file.name}'
            print('PASS: clean rebuild byte-identical, cmap union exact, disjoint, exclusions verified')
    else:
        report=build(ROOT/'public/fonts')
    print(json.dumps({k:report[k] for k in ['selectedCount','shardCount','woff2Bytes','maxShardBytes']},indent=2))

if __name__=='__main__':
    main()
